### ISSUE TITLE
Build on Raspberry pi zero w failed because of `mmal-sys`

### ISSUE THREAD

**Issue by exo-cortex** [pedrosland/rascam#11]
Hi, 
I tried to test this project on my raspberry pi zero w (the first one). I ran
```
$ cargo build --example simple
[ everything worked until: ]
   Compiling mmal-sys v0.1.0-3
error: failed to run custom build command for `mmal-sys v0.1.0-3`

Caused by:
  process didn't exit successfully: `/home/nt_user/rascam/target/debug/build/mmal-sys-287bf31682c36ace/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=mmal_util
  cargo:rustc-link-lib=mmal_core
  cargo:rustc-link-lib=mmal_vc_client
  cargo:rustc-link-lib=vcos
  cargo:rustc-link-lib=bcm_host
  cargo:rustc-link-lib=vchiq_arm
  cargo:rustc-link-lib=vcsm
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=MMAL_INCLUDE_DIR
  cargo:rerun-if-env-changed=MMAL_LIB_DIR

  --- stderr
  thread 'main' panicked at /home/nt_user/.cargo/registry/src/index.crates.io-1cd66030c949c28d/mmal-sys-0.1.0-3/build.rs:115:9:
  Could not locate libary.
  path: /opt/vc/lib
  default: /opt/vc/lib
  env MMAL_LIB_DIR: Err(NotPresent)

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am not sure what to do. Is this project supposed to be cross-compiled on another machine?

**Comment by pedrosland** [comment]
Hi exo-cortex,

Thanks for the issue!

mmal-sys expects libmmal to be in /opt/vc/lib and it seems like it isn't there on your system. This is normal.

Raspberry Pi have decided that mmal is not the way any more and have switched to using normal Linux APIs. They no longer include the library in the latest version of their OS. In fact some features of the fairly modern Pis eg Pi4's hardware H.265 are only available using the Linux APIs. They recommend the use of v4l or something built on top of it. I've not used a camera with the Pi for a long time so I can't recommend a library.

If you want to continue with mmal-sys/rascam then I think you can. I think the [bullseye aka legacy images](https://www.raspberrypi.com/software/operating-systems/) include it.

Alternatively you could try to copy the binaries to your current system and see what happens.
The old /opt/vc is available here as binaries: https://github.com/raspberrypi/firmware/tree/oldstable/opt/vc
The source code for (the parts you need of) that can be found here: https://github.com/raspberrypi/userland

> Is this project supposed to be cross-compiled on another machine?

It can be cross-compiled if you want but that is optional. If the libraries are in their default location it should just work. If you choose to cross-compile, make sure to install the right compiler and configure your IDE to use the right architecture for intellisense. You can override the default location for libmmal by setting the environment variable eg `MMAL_LIB_DIR=/some/path/to/vc/lib` in your shell.
