### ISSUE TITLE
Compilation is failing

### ISSUE THREAD

**Issue by valmirjunior0088** [pedrosland/rascam#2]
Compilation fails with the following message:

```
error[E0308]: mismatched types
   --> <redacted>/.cargo/git/checkouts/rascam-90a9922d5e6b52c6/3c2d378/src/lib.rs:690:17
    |
690 |                 ffi::MMAL_COMPONENT_NULL_SINK.as_ptr(),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i8, found u8
    |
    = note: expected type `*const i8`
               found type `*const u8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `rascam`.

To learn more, run the command again with --verbose.
```

This is how I found out about pedrosland/mmal-sys#8. I don't know if they're related but I think it's worth the mention.

**Comment by valmirjunior0088** [comment]
Following pedrosland/mmal0sys#8, I tried to build the project on the Pi and now it tries to pull an old version of `parking_lot_core` which fails to build:

```
   Compiling parking_lot_core v0.2.14
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.14/src/lib.rs:41:60
   |
41 | #![cfg_attr(all(feature = "nightly", target_os = "linux"), feature(integer_atomics))]
   |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `parking_lot_core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by pedrosland** [comment]
I fixed this some time ago but I didn't tag a release for some reason.
As a workaround, you should be able to use the master branch. I just compiled now so it should work :).

I made a couple of updates to mmal-sys during the week. Once I've tested them, I'll tag a mmal-sys version, update rascam and tag a version here.

**Comment by valmirjunior0088** [comment]
Thanks!

**Comment by pedrosland** [comment]
@valmirjunior0088 I finally finished some minor updates, testing and published both mmal-sys and rascam. v0.0.2 is now on crates.io so you don't need to fetch the dependency from github. I'm not aware of any changes to the API so it should just work.

Please let me know if you find any more problems.
